main/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('home/', views.home_view, name="home"),
    path('catalog/', views.catalog_view, name="catalog"),
    path('calculator/', views.calculator_view, name="calculator"),
    path('price/<str:type>/<int:pk>/<int:fab>/', views.price_view, name="price"),
    path('workers/', views.workers_view, name="workers"),
    path('net/<int:pk>/', views.net_view, name="net"),
    path('rolet/<int:pk>/', views.rolet_view, name="rolet"),
    path('net/<int:pk>/price/', views.net_price, name="net_price"),
    path('rolet/<int:pk>/price/', views.rolet_price, name="rolet_price"),
    path('fabric/<int:pk>/', views.fabric_view, name="fabric"),
]

rolety/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse_lazy, reverse

# Create your models here.


class Net(models.Model):
    name = models.CharField(verbose_name="Назва", max_length=500)
    c_name = models.CharField(default='net', editable=False)
    description = models.TextField(verbose_name="Опис", max_length=5000, blank=True, null=True)
    price_m = models.IntegerField(verbose_name="Ціна за метр")
    price = models.IntegerField(verbose_name='Ціна за встановлення')
    image = models.ImageField(verbose_name='Фото', upload_to='main/nets/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(self.c_name, args=[self.id])

    class Meta:
        verbose_name = 'Москітна сітка'
        verbose_name_plural = 'Москітні сітки'


class Fabric(models.Model):
    name = models.CharField(verbose_name='Назва',max_length=500)
    c_name = models.CharField(default='fabric', editable=False)
    description = models.TextField(verbose_name='Опис', max_length=5000, blank=True, null=True)
    price_m = models.IntegerField(verbose_name='Ціна за метр')
    image = models.ImageField(verbose_name='Фото', upload_to='main/fabrics/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(self.c_name, args=[self.id])

    class Meta:
        verbose_name = 'Тканина'
        verbose_name_plural = 'Тканини'


class Rolet(models.Model):
    name = models.CharField(verbose_name='Назва', max_length=500)
    c_name = models.CharField(default='rolet', editable=False)
    description = models.TextField(verbose_name='Опис', max_length=5000, blank=True, null=True)
    price_m = models.IntegerField(verbose_name='Ціна за метр', default=0)
    price = models.IntegerField(verbose_name='Ціна')
    fabric = models.ManyToManyField(Fabric, verbose_name='Доступні тканини')
    image = models.ImageField(verbose_name='Фото', upload_to='main/rolets/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(self.c_name, args=[self.id])

    class Meta:
        verbose_name = 'Ролет'
        verbose_name_plural = 'Ролети'


class Worker(models.Model):
    name = models.CharField(verbose_name="Ім'я", max_length=200)
    photo = models.ImageField(verbose_name='Фото', upload_to='main/workers')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Працівник'
        verbose_name_plural = 'Працівники'


class WorkerImage(models.Model):
    work_picture = models.ImageField(verbose_name='Фото', upload_to='main/workers_work')
    worker = models.ForeignKey(Worker, verbose_name='Працівник', on_delete=models.CASCADE)

    def __str__(self):
        return self.work_picture.url

    class Meta:
        verbose_name = 'Фото роботи'
        verbose_name_plural = 'Фото роботи'


class WindowType(models.Model):
    name = models.CharField(verbose_name='Назва', max_length=1000)
    price = models.IntegerField(verbose_name='Ціна')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тип вікна'
        verbose_name_plural = 'Типи вікон'


class WindowColour(models.Model):
    name = models.CharField(verbose_name='Назва', max_length=1000)
    price = models.IntegerField(verbose_name='Ціна')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Колір вікна'
        verbose_name_plural = 'Кольори вікон'

main/views.py
from django.shortcuts import render, redirect
from .models import Rolet, Fabric, Net, Worker, WindowType, WindowColour
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from itertools import chain
# Create your views here.


def home_view(request):
    context = {
        'request': request,
    }
    return render(request, "main/home.html", context=context)


def catalog_view(request):
    context = {'request': request,
               }
    if request.GET == {}:
        nets = Net.objects.all()
        rolets = Rolet.objects.all()
        context['nets'] = 'nets'
        context['rolets'] = 'rolets'
        context['search_text'] = ''
        all_objects = rolets.union(nets)
    else:
        if request.GET.get('search_text'):
            context['search_text'] = request.GET.get('search_text')
        else:
            context['search_text'] = ''
        if request.GET.get('nets') == 'nets':
            context['nets'] = 'nets'
            nets = Net.objects.all()
            if request.GET.get('search_text'):
                nets = nets.filter(name__icontains=request.GET.get('search_text'))
            if request.GET.get('rolets') == 'rolets':
                context['rolets'] = 'rolets'
                rolets = Rolet.objects.all()
                if request.GET.get('search_text'):
                    rolets = rolets.filter(name__icontains=request.GET.get('search_text'))
                all_objects = rolets.union(nets)
            else:
                context['rolets'] = ''
                all_objects = nets
        else:
            context['nets'] = ''
            if request.GET.get('rolets') == 'rolets':
                context['rolets'] = 'rolets'
                rolets = Rolet.objects.all()
                if request.GET.get('search_text'):
                    rolets = rolets.filter(name__icontains=request.GET.get('search_text'))
                all_objects = rolets
            else:
                context['rolets'] = ''

    all_objects = all_objects.order_by('id')
    paginator = Paginator(all_objects, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context['page_obj'] = page_obj

    return render(request, "main/catalog.html", context=context)


def calculator_view(request):
    context = {'request': request,
               }
    if request.GET == {}:
        nets = Net.objects.all()
        rolets = Rolet.objects.all()
        context['nets'] = 'nets'
        context['rolets'] = 'rolets'
        context['search_text'] = ''
        all_objects = rolets.union(nets)
    else:
        if request.GET.get('search_text'):
            context['search_text'] = request.GET.get('search_text')
        else:
            context['search_text'] = ''
        if request.GET.get('nets') == 'nets':
            context['nets'] = 'nets'
            nets = Net.objects.all()
            if request.GET.get('search_text'):
                nets = nets.filter(name__icontains=request.GET.get('search_text'))
            if request.GET.get('rolets') == 'rolets':
                context['rolets'] = 'rolets'
                rolets = Rolet.objects.all()
                if request.GET.get('search_text'):
                    rolets = rolets.filter(name__icontains=request.GET.get('search_text'))
                all_objects = rolets.union(nets)
            else:
                context['rolets'] = ''
                all_objects = nets
        else:
            context['nets'] = ''
            if request.GET.get('rolets') == 'rolets':
                context['rolets'] = 'rolets'
                rolets = Rolet.objects.all()
                if request.GET.get('search_text'):
                    rolets = rolets.filter(name__icontains=request.GET.get('search_text'))
                all_objects = rolets
            else:
                context['rolets'] = ''

    all_objects = all_objects.order_by('id')
    paginator = Paginator(all_objects, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context['page_obj'] = page_obj

    return render(request, "main/calculator.html", context=context)


def price_view(request, type, pk, fab):
    context = {
        'request': request,
        'colours': WindowColour.objects.all(),
        'types': WindowType.objects.all(),
    }
    price = 0
    if request.method == 'POST':
        w_type = int(request.POST.get('w_type'))
        w_colour = int(request.POST.get('w_colour'))
        h = int(request.POST.get('height'))
        w = int(request.POST.get('width'))
        w_type = WindowType.objects.get(id=w_type)
        w_colour = WindowColour.objects.get(id=w_colour)
        area = h*w/100
        price += w_type.price
        price += w_colour.price
        if type == 'rolet':
            rol = Rolet.objects.get(id=pk)
            fabric = Fabric.objects.get(id=fab)
            price += rol.price
            price += fabric.price_m*area
        elif type == 'net':
            net = Net.objects.get(id=pk)
            price += net.price
            price += net.price_m * area
    context['price']=price
    return render(request, "main/price.html", context=context)


def workers_view(request):
    context = {
        'request': request,
        'workers': Worker.objects.all(),
    }
    return render(request, "main/workers.html", context=context)


def net_view(request, pk):
    context = {
        'request': request,
        'net': Net.objects.get(id=pk),
    }
    return render(request, "main/net.html", context=context)


def rolet_view(request, pk):
    context = {
        'request': request,
        'rolet': Rolet.objects.get(id=pk),
    }
    return render(request, "main/rolet.html", context=context)


def net_price(request, pk):
    return redirect('price', type='net', pk=pk, fab='0')


def rolet_price(request, pk):
    context = {
        'request': request,
        'rolet': Rolet.objects.get(id=pk),
    }
    return render(request, "main/rolet_price.html", context=context)


def fabric_view(request, pk):
    context = {
        'request': request,
        'fabric': Fabric.objects.get(id=pk),
    }
    return render(request, "main/fabric.html", context=context)

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8"/>
    <title>Shadeline</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/main/css/base.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <div class="content header" id="header_content">
        <div class="header">
            <div class="header1">
                <img id=main_icon class="main_icon" src="{% static '/main/img/window.png'%}">
                <p class="wname">Shadeline</p>
                <ul class="nav">
                    <li class="nav_el">
                        <a href="{% url 'home'%}">
                        {% if request.path == "/main/home/"%}
                        <p class="current_page">Головна</p>
                        {%else%}
                        <p>Головна</p>
                        {%endif%}
                        </a>
                    </li>
                    <li class="nav_el">
                        <a href="{% url 'catalog'%}">
                        {% if request.path == "/main/catalog/"%}
                        <p class="current_page">Каталог</p>
                        {%else%}
                        <p>Каталог</p>
                        {%endif%}
                        </a>
                    </li>
                    <li class="nav_el">
                        <a href="{% url 'workers'%}">
                        {% if request.path == "/main/workers/"%}
                        <p class="current_page">Наша команда</p>
                        {%else%}
                        <p>Наша команда</p>
                        {%endif%}
                        </a>
                    </li>
                    <li class="nav_el">
                        <a href="{% url 'calculator'%}">
                        {% if request.path == "/main/calculator/"%}
                        <p class="current_page">Калькулятор цін</p>
                        {%else%}
                        <p>Калькулятор цін</p>
                        {%endif%}
                        </a>
                    </li>
                </ul>
                <button class="menu_open">
                    <img class="hamburger" src="{% static '/main/img/menu.png'%}">
                </button>
            </div>
        </div>
    </div>
</header>
<section id="headc" class="header2">
    <p class="header2_1">Для замовлення телефонуйте:</p>
    <ul class="header2_2">
        <li class="contacts_el">
            <p class="contacts_el1">Наші контакти:</p>
        </li>
        <li class="contacts_el">
            <p class="contacts_el1">0665047525</p>
        </li>
        <li class="contacts_el">
            <p class="contacts_el1">0977522799</p>
        </li>
    </ul>
</section>
{% block content %}
{% endblock %}
<footer>
    <div class="content home footer">
        <div class="footer1">
            <p class="footerH one">Наші контакти:</p>
            <p class="footerL">gora.melnik@gmail.com</p>
            <p class="footerL">0665047525</p>
        </div>
        <div class="footer1">
            <p class="footerH">Адреси магазинів:</p>
            <p class="footerL">вул. Шевченка 15</p>
            <p class="footerL">вул. Грушевського 23</p>
        </div>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
let elementsArray = document.querySelectorAll("section");
console.log(elementsArray);
window.addEventListener('scroll', fadeIn ); 
function fadeIn() {
    for (var i = 0; i < elementsArray.length; i++) {
        var elem = elementsArray[i]
        var distInView = elem.getBoundingClientRect().top - window.innerHeight + 20;
        if (distInView < 0) {
            elem.classList.add("inView");
        } else {
            elem.classList.remove("inView");
        }
    }
}
fadeIn();
</script>
<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
<script src="{% static 'main/js/base.js'%}"></script>
</body>
</html>

main/templates/main/calculator.html
{% extends "main/base.html" %}
{% block content%}
{% load static %}
<section class="home4 cat">
    <div class="content cat">
        <p class="heading_calc">Оберіть товар:</p>
        <form id="form1" class="search_c calc" action="{% url 'catalog'%}" method="get">
            <p class="cat_heading">Категорії:</p>
            <div class="cat">
                <div class="category">
                    {% if nets == 'nets' %}
                    <input type="checkbox" onclick="submitf()" form="form1" class="cross_img" id="nets" name="nets" value="nets" checked>
                    {% else %}
                    <input type="checkbox" onclick="submitf()" form="form1" class="cross_img" id="nets" name="nets" value="nets">
                    {% endif %}
                    <p class="cat_text">Москітні сітки</p>
                </div>
                <div class="category">
                    {% if rolets == 'rolets' %}
                    <input type="checkbox" onclick="submitf()" form="form1" class="cross_img" id="rolets" name="rolets" value="rolets" checked>
                    {% else %}
                    <input type="checkbox" onclick="submitf()" form="form1" class="cross_img" id="rolets" name="rolets" value="rolets">
                    {% endif %}
                    <p class="cat_text" id="rolet_t">Ролети</p>
                </div>
            </div>
            <div class="search">
                <button type="submit" form="form1" class="empty_button">
                    <img class="search_img" src="{% static 'main/img/glass.png'%}">
                </button>
                <input id="search_text" name="search_text" form="form1" type="text" class="search_input" placeholder="пошук ...">
            </div>
        </form>
        <div class="grid first">
            <div class="row">
                {% for obj in page_obj.object_list|slice:"0:5" %}
                <a href="{{ obj.get_absolute_url}}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
            <div class="row">
                {% for obj in page_obj.object_list|slice:"5:10" %}
                <a href="{{ obj.get_absolute_url }}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="grid second">
            <div class="row">
                {% for obj in page_obj.object_list|slice:"0:3" %}
                <a href="{{ obj.get_absolute_url }}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
            <div class="row">
                {% for obj in page_obj.object_list|slice:"3:6" %}
                <a href="{{ obj.get_absolute_url }}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
            <div class="row">
                {% for obj in page_obj.object_list|slice:"6:9" %}
                <a href="{{ obj.get_absolute_url }}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
            <div class="row">
                {% for obj in page_obj.object_list|slice:"9:" %}
                <a href="{{ obj.get_absolute_url }}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="grid third">
            <div class="row">
                {% for obj in page_obj.object_list|slice:"0:2" %}
                <a href="{{ obj.get_absolute_url }}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
            <div class="row">
                {% for obj in page_obj.object_list|slice:"2:4" %}
                <a href="{{ obj.get_absolute_url }}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
            <div class="row">
                {% for obj in page_obj.object_list|slice:"4:6" %}
                <a href="{{ obj.get_absolute_url }}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
            <div class="row">
                {% for obj in page_obj.object_list|slice:"6:8" %}
                <a href="{{ obj.get_absolute_url }}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
            <div class="row">
                {% for obj in page_obj.object_list|slice:"8:" %}
                <a href="{{ obj.get_absolute_url }}price/">
                <div class="card">
                    <img class="net_img" src="{{ obj.image.url }}">
                    <p class="name_text">{{ obj.name }}</p>
                    {% if obj.c_name == 'net'%}
                    <p class="price_text">{{ obj.price_m }} грн/кв.м.</p>
                    {% endif %}
                </div>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="pagination cat">
            {% if page_obj.has_previous %}
            <a href="?nets={{nets}}&rolets={{rolets}}&search_text={{search_text}}&page={{ page_obj.previous_page_number }}">
                <div class="p_item" style="background-image: url({% static 'main/img/arrowl.png'%});">
                </div>
            </a>
            <a href="?nets={{nets}}&rolets={{rolets}}&search_text={{search_text}}&page={{ page_obj.previous_page_number }}">
                <div class="p_item" style="background-image: url({% static 'main/img/pagin1.png'%});">
                    {{ page_obj.previous_page_number }}
                </div>
            </a>
            {% endif %}
            <div class="p_item current" style="background-image: url({% static 'main/img/pagin2.png'%});">
                {{ page_obj.number }}
            </div>
            {% if page_obj.has_next %}
            <a href="?nets={{nets}}&rolets={{rolets}}&search_text={{search_text}}&page={{ page_obj.next_page_number }}">
                <div class="p_item" style="background-image: url({% static 'main/img/pagin1.png'%});">
                    {{ page_obj.next_page_number }}
                </div>
            </a>
            <a href="?nets={{nets}}&rolets={{rolets}}&search_text={{search_text}}&page={{ page_obj.next_page_number }}">
                <div class="p_item last" style="background-image: url({% static 'main/img/arrowr.png'%});">
                </div>
            </a>
            {% endif %}
        </div>
    </div>
    <script>
        function submitf() {
            document.forms['form1'].submit();
        }
    </script>
</section>
{% endblock %}

main/templates/main/fabric.html
{% extends "main/base.html" %}
{% block content%}
{% load static %}
<section class="home4">
    <div class="content obj">
        <div class="obj_wrapper">
            <div class="obj_img_wrapper net">
            <img class="obj_img net" src="{{fabric.image.url}}">
            </div>
            <div class="about_obj">
                <p class="obj_title">{{fabric.name}}</p>
                <p class="obj_price_m">{{fabric.price_m}} грн/кв.м.</p>
                <p class="obj_description">{{fabric.description}}</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

main/templates/main/net.html
{% extends "main/base.html" %}
{% block content%}
{% load static %}
<section class="home4 r">
    <div class="content obj">
        <div class="obj_wrapper">
            <div class="obj_img_wrapper net">
            <img class="obj_img net" src="{{net.image.url}}">
            </div>
            <div class="about_obj">
                <p class="obj_title">{{net.name}}</p>
                <p class="obj_price_m">{{net.price_m}} грн/кв.м.</p>
                <p class="obj_price">Ціна встановлення: {{net.price}} грн</p>
                <p class="obj_description">{{net.description}}</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

main/templates/main/workers.html
{% extends "main/base.html" %}
{% block content%}
{% load static %}
{% for worker in workers %}
<section class="home4 small work">
    <div class="content workers">
        <div class="work_col">
            <p class="work_heading">{{worker.name}}</p>
            <img class="work_img" src="{{worker.photo.url}}">
        </div>
        <div class="work_col">
            <p class="work_heading">Приклади робіт:</p>
            <div class="car_wrapper">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        {% with worker.workerimage_set.all as imageset %}
                    <ol class="carousel-indicators">
                        {% with imageset|first as fimg %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        {% endwith %}
                        {% for image in imageset|slice:"1:" %} 
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% with imageset|first as fimg %}
                        <div class="carousel-item active">
                        <img class="d-block w-100" src="{{fimg.work_picture.url}}" alt="First slide">
                        </div>
                        {% endwith %} 
                        {% for image in imageset|slice:"1:" %}
                        <div class="carousel-item">
                        <img class="d-block w-100" src="{{image.work_picture.url}}" alt="First slide">
                        </div>
                        {% endfor %}
                        {% endwith %} 
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endfor %}
{% endblock %}